# Generated by Django 5.2.3 on 2025-06-17 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosAdjuntos',
            fields=[
                ('iddocumentoadjunto', models.AutoField(db_column='IDDocumentoAdjunto', primary_key=True, serialize=False)),
                ('nombredocumento', models.CharField(db_column='NombreDocumento', max_length=255)),
                ('archivodocumento', models.FileField(db_column='ArchivoDocumento', upload_to='documentos/%Y/%m/%d/')),
                ('fechacarga', models.DateTimeField(auto_now_add=True, db_column='FechaCarga')),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
                ('entidadasociada', models.CharField(db_column='EntidadAsociada', max_length=50)),
                ('identidadasociada', models.IntegerField(db_column='IDEntidadAsociada')),
            ],
            options={
                'db_table': 'documentosadjuntos',
            },
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('idespecialidad', models.AutoField(db_column='IDEspecialidad', primary_key=True, serialize=False)),
                ('nombreespecialidad', models.CharField(db_column='NombreEspecialidad', max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'especialidades',
            },
        ),
        migrations.CreateModel(
            name='EstadosEquipo',
            fields=[
                ('idestatus', models.AutoField(db_column='IDEstado', primary_key=True, serialize=False)),
                ('nombreestado', models.CharField(db_column='NombreEstado', max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Estado de Equipo',
                'verbose_name_plural': 'Estados de Equipo',
                'db_table': 'estadosequipo',
            },
        ),
        migrations.CreateModel(
            name='EstadosOrdenTrabajo',
            fields=[
                ('idestado', models.AutoField(db_column='IDEstado', primary_key=True, serialize=False)),
                ('nombreestado', models.CharField(db_column='NombreEstado', max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Estado de Orden de Trabajo',
                'verbose_name_plural': 'Estados de Orden de Trabajo',
                'db_table': 'estadosordentrabajo',
            },
        ),
        migrations.CreateModel(
            name='Faenas',
            fields=[
                ('idfaena', models.AutoField(db_column='IDFaena', primary_key=True, serialize=False)),
                ('nombrefaena', models.CharField(db_column='NombreFaena', max_length=100, unique=True)),
                ('ubicacion', models.CharField(blank=True, db_column='Ubicacion', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Faena',
                'verbose_name_plural': 'Faenas',
                'db_table': 'faenas',
            },
        ),
        migrations.CreateModel(
            name='Repuestos',
            fields=[
                ('idrepuesto', models.AutoField(db_column='IDRepuesto', primary_key=True, serialize=False)),
                ('numeroparte', models.CharField(db_column='NumeroParte', max_length=50, unique=True)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=255)),
                ('stockactual', models.IntegerField(db_column='StockActual')),
                ('stockminimo', models.IntegerField(blank=True, db_column='StockMinimo', null=True)),
                ('unidadmedida', models.CharField(db_column='UnidadMedida', max_length=20)),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos',
                'db_table': 'repuestos',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('idrol', models.AutoField(db_column='IDRol', primary_key=True, serialize=False)),
                ('nombrerol', models.CharField(db_column='NombreRol', max_length=50, unique=True)),
                ('descripcionrol', models.CharField(blank=True, db_column='DescripcionRol', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='TiposEquipo',
            fields=[
                ('idtipoequipo', models.AutoField(db_column='IDTipoEquipo', primary_key=True, serialize=False)),
                ('nombretipo', models.CharField(db_column='NombreTipo', max_length=100)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Equipo',
                'verbose_name_plural': 'Tipos de Equipo',
                'db_table': 'tiposequipo',
            },
        ),
        migrations.CreateModel(
            name='TiposMantenimientoOT',
            fields=[
                ('idtipomantenimientoot', models.AutoField(db_column='IDTipoMantenimientoOT', primary_key=True, serialize=False)),
                ('nombretipomantenimiento', models.CharField(db_column='NombreTipoMantenimiento', max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Mantenimiento para OT',
                'verbose_name_plural': 'Tipos de Mantenimiento para OT',
                'db_table': 'tiposmantenimientoot',
            },
        ),
        migrations.CreateModel(
            name='TiposTarea',
            fields=[
                ('idtipotarea', models.AutoField(db_column='IDTipoTarea', primary_key=True, serialize=False)),
                ('nombretipotarea', models.CharField(db_column='NombreTipoTarea', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Tarea',
                'verbose_name_plural': 'Tipos de Tarea',
                'db_table': 'tipostarea',
            },
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('idequipo', models.AutoField(db_column='IDEquipo', primary_key=True, serialize=False)),
                ('codigoequipo', models.CharField(db_column='CodigoEquipo', max_length=50, unique=True)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=255)),
                ('horometroactual', models.IntegerField(blank=True, db_column='HorometroActual', null=True)),
                ('idestatus', models.ForeignKey(db_column='IDEstado', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.estadosequipo')),
                ('idfaena', models.ForeignKey(db_column='IDFaena', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.faenas')),
                ('idtipoequipo', models.ForeignKey(db_column='IDTipoEquipo', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.tiposequipo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipos',
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadosEquipo',
            fields=[
                ('idhistorialestado', models.AutoField(db_column='IDHistorialEstado', primary_key=True, serialize=False)),
                ('fechainicio', models.DateTimeField(db_column='FechaInicio')),
                ('fechafin', models.DateTimeField(blank=True, db_column='FechaFin', null=True)),
                ('idequipo', models.ForeignKey(db_column='IDEquipo', on_delete=django.db.models.deletion.CASCADE, to='cmms_api.equipos')),
                ('idestado', models.ForeignKey(db_column='IDEstado', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.estadosequipo')),
            ],
            options={
                'verbose_name': 'Historial de Estado de Equipo',
                'verbose_name_plural': 'Historial de Estados de Equipo',
                'db_table': 'historialestadosequipo',
            },
        ),
        migrations.CreateModel(
            name='HistorialHorometros',
            fields=[
                ('idhistorialhorometro', models.AutoField(db_column='IDHistorialHorometro', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('valorhorometro', models.IntegerField(db_column='ValorHorometro')),
                ('idequipo', models.ForeignKey(db_column='IDEquipo', on_delete=django.db.models.deletion.CASCADE, to='cmms_api.equipos')),
            ],
            options={
                'verbose_name': 'Historial de Horómetro',
                'verbose_name_plural': 'Historial de Horómetros',
                'db_table': 'historialhorometros',
            },
        ),
        migrations.CreateModel(
            name='OrdenesTrabajo',
            fields=[
                ('idordentrabajo', models.AutoField(db_column='IDOrdenTrabajo', primary_key=True, serialize=False)),
                ('descripcionot', models.CharField(db_column='DescripcionOT', max_length=255)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('fechainicioprogramado', models.DateTimeField(blank=True, db_column='FechaInicioProgramado', null=True)),
                ('fechafinprogramado', models.DateTimeField(blank=True, db_column='FechaFinProgramado', null=True)),
                ('fechainicioreal', models.DateTimeField(blank=True, db_column='FechaInicioReal', null=True)),
                ('fechafinreal', models.DateTimeField(blank=True, db_column='FechaFinReal', null=True)),
                ('idequipo', models.ForeignKey(db_column='IDEquipo', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.equipos')),
                ('idestado', models.ForeignKey(db_column='IDEstado', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.estadosordentrabajo')),
                ('idfaena', models.ForeignKey(db_column='IDFaena', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.faenas')),
                ('idtipomantenimiento', models.ForeignKey(db_column='IDTipoMantenimientoOT', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.tiposmantenimientoot')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Ordenes de Trabajo',
                'db_table': 'ordenestrabajo',
            },
        ),
        migrations.CreateModel(
            name='TareasEstandar',
            fields=[
                ('idtareaestandar', models.AutoField(db_column='IDTareaEstandar', primary_key=True, serialize=False)),
                ('codigotarea', models.CharField(db_column='CodigoTarea', max_length=20, unique=True)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=255)),
                ('duracionestimadahoras', models.DecimalField(db_column='DuracionEstimadaHoras', decimal_places=2, max_digits=5)),
                ('idespecialidadrequerida', models.ForeignKey(blank=True, db_column='IDEspecialidadRequerida', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms_api.especialidades')),
                ('idtipotarea', models.ForeignKey(db_column='IDTipoTarea', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.tipostarea')),
            ],
            options={
                'verbose_name': 'Tarea Estándar',
                'verbose_name_plural': 'Tareas Estándar',
                'db_table': 'tareasestandar',
            },
        ),
        migrations.CreateModel(
            name='ActividadesOrdenTrabajo',
            fields=[
                ('idactividadot', models.AutoField(db_column='IDActividadOT', primary_key=True, serialize=False)),
                ('observaciones', models.TextField(blank=True, db_column='Observaciones', null=True)),
                ('completada', models.BooleanField(db_column='Completada', default=False)),
                ('fechacompletada', models.DateTimeField(blank=True, db_column='FechaCompletada', null=True)),
                ('idordentrabajo', models.ForeignKey(db_column='IDOrdenTrabajo', on_delete=django.db.models.deletion.CASCADE, to='cmms_api.ordenestrabajo')),
                ('idtareaestandar', models.ForeignKey(db_column='IDTareaEstandar', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.tareasestandar')),
            ],
            options={
                'verbose_name': 'Actividad de Orden de Trabajo',
                'verbose_name_plural': 'Actividades de Ordenes de Trabajo',
                'db_table': 'actividadesordentrabajo',
            },
        ),
        migrations.CreateModel(
            name='PlanesMantenimiento',
            fields=[
                ('idplanmantenimiento', models.AutoField(db_column='IDPlanMantenimiento', primary_key=True, serialize=False)),
                ('nombreplan', models.CharField(db_column='NombrePlan', max_length=100)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
                ('idtipoequipo', models.ForeignKey(db_column='IDTipoEquipo', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.tiposequipo')),
            ],
            options={
                'verbose_name': 'Plan de Mantenimiento',
                'verbose_name_plural': 'Planes de Mantenimiento',
                'db_table': 'planesmantenimiento',
            },
        ),
        migrations.CreateModel(
            name='UsoRepuestosActividadOT',
            fields=[
                ('idusorepuesto', models.AutoField(db_column='IDUsoRepuesto', primary_key=True, serialize=False)),
                ('cantidadutilizada', models.IntegerField(db_column='CantidadUtilizada')),
                ('idactividadot', models.ForeignKey(db_column='IDActividadOT', on_delete=django.db.models.deletion.CASCADE, to='cmms_api.actividadesordentrabajo')),
                ('idrepuesto', models.ForeignKey(db_column='IDRepuesto', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.repuestos')),
            ],
            options={
                'verbose_name': 'Uso de Repuesto en Actividad',
                'verbose_name_plural': 'Uso de Repuestos en Actividades',
                'db_table': 'usorepuestosactividadot',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idusuario', models.OneToOneField(db_column='IDUsuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('idespecialidad', models.ForeignKey(blank=True, db_column='IDEspecialidad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms_api.especialidades')),
                ('idrol', models.ForeignKey(db_column='IDRol', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.roles')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.AddField(
            model_name='ordenestrabajo',
            name='idusuariocreador',
            field=models.ForeignKey(blank=True, db_column='IDUsuarioCreador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_creadas', to='cmms_api.usuarios'),
        ),
        migrations.AddField(
            model_name='ordenestrabajo',
            name='idusuariosupervisor',
            field=models.ForeignKey(blank=True, db_column='IDUsuarioSupervisor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_supervisadas', to='cmms_api.usuarios'),
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('idnotificacion', models.AutoField(db_column='IDNotificacion', primary_key=True, serialize=False)),
                ('mensaje', models.TextField(db_column='Mensaje')),
                ('tiponotificacion', models.CharField(blank=True, db_column='TipoNotificacion', max_length=50, null=True)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('fechalectura', models.DateTimeField(blank=True, db_column='FechaLectura', null=True)),
                ('leida', models.BooleanField(db_column='Leida', default=False)),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], db_column='Prioridad', default='Media', max_length=5)),
                ('urlrelacionada', models.CharField(blank=True, db_column='URLRelacionada', max_length=255, null=True)),
                ('idusuariodestino', models.ForeignKey(db_column='IDUsuarioDestino', on_delete=django.db.models.deletion.CASCADE, to='cmms_api.usuarios')),
            ],
            options={
                'db_table': 'notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Agendas',
            fields=[
                ('idagenda', models.AutoField(db_column='IDAgenda', primary_key=True, serialize=False)),
                ('tituloevento', models.CharField(db_column='TituloEvento', max_length=255)),
                ('descripcionevento', models.TextField(blank=True, db_column='DescripcionEvento', null=True)),
                ('fechahorainicio', models.DateTimeField(db_column='FechaHoraInicio')),
                ('fechahorafin', models.DateTimeField(db_column='FechaHoraFin')),
                ('tipoevento', models.CharField(blank=True, db_column='TipoEvento', max_length=50, null=True)),
                ('idequipo', models.ForeignKey(blank=True, db_column='IDEquipo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms_api.equipos')),
                ('idordentrabajo', models.ForeignKey(blank=True, db_column='IDOrdenTrabajo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms_api.ordenestrabajo')),
                ('idusuarioasignado', models.ForeignKey(blank=True, db_column='IDUsuarioAsignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_asignados', to='cmms_api.usuarios')),
                ('idusuariocreador', models.ForeignKey(blank=True, db_column='IDUsuarioCreador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_creados', to='cmms_api.usuarios')),
            ],
            options={
                'db_table': 'agendas',
            },
        ),
        migrations.AddField(
            model_name='actividadesordentrabajo',
            name='idtecnicoejecutor',
            field=models.ForeignKey(blank=True, db_column='IDTecnicoEjecutor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms_api.usuarios'),
        ),
        migrations.CreateModel(
            name='DetallesPlanMantenimiento',
            fields=[
                ('iddetalleplan', models.AutoField(db_column='IDDetallePlan', primary_key=True, serialize=False)),
                ('puntomantenimiento', models.CharField(blank=True, db_column='PuntoMantenimiento', max_length=20, null=True)),
                ('intervalohorasoperacion', models.IntegerField(blank=True, db_column='IntervaloHorasOperacion', null=True)),
                ('intervalodiascalendario', models.IntegerField(blank=True, db_column='IntervaloDiasCalendario', null=True)),
                ('tipointervalopredominante', models.CharField(blank=True, db_column='TipoIntervaloPredominante', max_length=5, null=True)),
                ('toleranciahoras', models.IntegerField(blank=True, db_column='ToleranciaHoras', null=True)),
                ('toleranciadiana', models.IntegerField(blank=True, db_column='ToleranciaDias', null=True)),
                ('idplanmantenimiento', models.ForeignKey(db_column='IDPlanMantenimiento', on_delete=django.db.models.deletion.CASCADE, to='cmms_api.planesmantenimiento')),
                ('idtareaestandar', models.ForeignKey(db_column='IDTareaEstandar', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.tareasestandar')),
            ],
            options={
                'verbose_name': 'Detalle de Plan de Mantenimiento',
                'verbose_name_plural': 'Detalles de Planes de Mantenimiento',
                'db_table': 'detallesplanmantenimiento',
                'unique_together': {('idplanmantenimiento', 'idtareaestandar')},
            },
        ),
    ]
