# Generated by Django 5.2.3 on 2025-06-19 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('idespecialidad', models.AutoField(db_column='IDEspecialidad', primary_key=True, serialize=False)),
                ('nombreespecialidad', models.CharField(db_column='NombreEspecialidad', max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'especialidades',
            },
        ),
        migrations.CreateModel(
            name='EstadosEquipo',
            fields=[
                ('idestadoequipo', models.AutoField(db_column='IDEstadoEquipo', primary_key=True, serialize=False)),
                ('nombreestado', models.CharField(db_column='NombreEstado', max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'estadosequipo',
            },
        ),
        migrations.CreateModel(
            name='EstadosOrdenTrabajo',
            fields=[
                ('idestadoot', models.AutoField(db_column='IDEstadoOT', primary_key=True, serialize=False)),
                ('nombreestadoot', models.CharField(db_column='NombreEstadoOT', max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'estadosordentrabajo',
            },
        ),
        migrations.CreateModel(
            name='Faenas',
            fields=[
                ('idfaena', models.AutoField(db_column='IDFaena', primary_key=True, serialize=False)),
                ('nombrefaena', models.CharField(db_column='NombreFaena', max_length=100, unique=True)),
                ('ubicacion', models.CharField(blank=True, db_column='Ubicacion', max_length=255, null=True)),
                ('contacto', models.CharField(blank=True, db_column='Contacto', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('activa', models.BooleanField(db_column='Activa', default=True)),
            ],
            options={
                'db_table': 'faenas',
            },
        ),
        migrations.CreateModel(
            name='PlanesMantenimiento',
            fields=[
                ('idplanmantenimiento', models.AutoField(db_column='IDPlanMantenimiento', primary_key=True, serialize=False)),
                ('nombreplan', models.CharField(db_column='NombrePlan', max_length=150)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'db_table': 'planesmantenimiento',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('idrol', models.AutoField(db_column='IDRol', primary_key=True, serialize=False)),
                ('nombrerol', models.CharField(db_column='NombreRol', max_length=50, unique=True)),
                ('descripcionrol', models.CharField(blank=True, db_column='DescripcionRol', max_length=255, null=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='TareasEstandar',
            fields=[
                ('idtareaestandar', models.AutoField(db_column='IDTareaEstandar', primary_key=True, serialize=False)),
                ('descripciontarea', models.CharField(db_column='DescripcionTarea', max_length=255)),
                ('procedimiento', models.CharField(blank=True, db_column='Procedimiento', max_length=255, null=True)),
                ('activa', models.BooleanField(db_column='Activa', default=True)),
            ],
            options={
                'db_table': 'tareasestandar',
            },
        ),
        migrations.CreateModel(
            name='TiposEquipo',
            fields=[
                ('idtipoequipo', models.AutoField(db_column='IDTipoEquipo', primary_key=True, serialize=False)),
                ('nombretipo', models.CharField(db_column='NombreTipo', max_length=100, unique=True)),
                ('descripciontipo', models.CharField(blank=True, db_column='DescripcionTipo', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tiposequipo',
            },
        ),
        migrations.CreateModel(
            name='TiposMantenimientoOT',
            fields=[
                ('idtipomantenimientoot', models.AutoField(db_column='IDTipoMantenimientoOT', primary_key=True, serialize=False)),
                ('nombretipomantenimientoot', models.CharField(db_column='NombreTipoMantenimientoOT', max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tiposmantenimientoot',
            },
        ),
        migrations.CreateModel(
            name='TiposTarea',
            fields=[
                ('idtipotarea', models.AutoField(db_column='IDTipoTarea', primary_key=True, serialize=False)),
                ('nombretipotarea', models.CharField(db_column='NombreTipoTarea', max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tipostarea',
            },
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('idequipo', models.AutoField(db_column='IDEquipo', primary_key=True, serialize=False)),
                ('codigointerno', models.CharField(db_column='CodigoInterno', max_length=50, unique=True)),
                ('nombreequipo', models.CharField(db_column='NombreEquipo', max_length=150)),
                ('marca', models.CharField(blank=True, db_column='Marca', max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, db_column='Modelo', max_length=100, null=True)),
                ('horometroactual', models.IntegerField(db_column='HorometroActual', default=0)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
                ('idestadoactual', models.ForeignKey(db_column='IDEstadoActual', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.estadosequipo')),
                ('idfaenaactual', models.ForeignKey(blank=True, db_column='IDFaenaActual', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms_api.faenas')),
                ('idtipoequipo', models.ForeignKey(db_column='IDTipoEquipo', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.tiposequipo')),
            ],
            options={
                'db_table': 'equipos',
            },
        ),
        migrations.CreateModel(
            name='OrdenesTrabajo',
            fields=[
                ('idordentrabajo', models.AutoField(db_column='IDOrdenTrabajo', primary_key=True, serialize=False)),
                ('numeroot', models.CharField(db_column='NumeroOT', max_length=20, unique=True)),
                ('fechacreacionot', models.DateTimeField(auto_now_add=True, db_column='FechaCreacionOT')),
                ('fechaemision', models.DateField(blank=True, db_column='FechaEmision', null=True)),
                ('fechaejecucion', models.DateField(blank=True, db_column='FechaEjecucion', null=True)),
                ('horometro', models.IntegerField(blank=True, db_column='Horometro', null=True)),
                ('observacionesgenerales', models.TextField(blank=True, db_column='ObservacionesGenerales', null=True)),
                ('firma_tecnico', models.CharField(blank=True, help_text='Nombre del técnico que firma al concluir.', max_length=150, null=True)),
                ('firma_solicitante', models.CharField(blank=True, help_text='Nombre del solicitante que firma.', max_length=150, null=True)),
                ('fechaautorizacion', models.DateField(blank=True, db_column='FechaAutorizacion', null=True)),
                ('idautorizadopor', models.ForeignKey(blank=True, db_column='IDAutorizadoPor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('idequipo', models.ForeignKey(db_column='IDEquipo', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.equipos')),
                ('idestadoot', models.ForeignKey(db_column='IDEstadoOT', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.estadosordentrabajo')),
                ('idsolicitante', models.ForeignKey(db_column='IDSolicitante', on_delete=django.db.models.deletion.PROTECT, related_name='ots_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('idtecnicoasignado', models.ForeignKey(db_column='IDTecnicoAsignado', on_delete=django.db.models.deletion.PROTECT, related_name='ots_asignadas', to=settings.AUTH_USER_MODEL)),
                ('idplanorigen', models.ForeignKey(blank=True, db_column='IDPlanOrigen', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms_api.planesmantenimiento')),
                ('idtipomantenimientoot', models.ForeignKey(db_column='IDTipoMantenimientoOT', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.tiposmantenimientoot')),
            ],
            options={
                'db_table': 'ordenestrabajo',
            },
        ),
        migrations.CreateModel(
            name='Agendas',
            fields=[
                ('idagenda', models.AutoField(db_column='IDAgenda', primary_key=True, serialize=False)),
                ('tituloevento', models.CharField(db_column='TituloEvento', max_length=255)),
                ('fechahorainicio', models.DateTimeField(db_column='FechaHoraInicio')),
                ('fechahorafin', models.DateTimeField(db_column='FechaHoraFin')),
                ('tipoevento', models.CharField(blank=True, db_column='TipoEvento', max_length=50, null=True)),
                ('descripcionevento', models.TextField(blank=True, db_column='DescripcionEvento', null=True)),
                ('idordentrabajo', models.ForeignKey(blank=True, db_column='IDOrdenTrabajo', null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms_api.ordenestrabajo')),
            ],
            options={
                'db_table': 'agendas',
            },
        ),
        migrations.CreateModel(
            name='ActividadesOrdenTrabajo',
            fields=[
                ('idactividadot', models.AutoField(db_column='IDActividadOT', primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, db_column='Estado', help_text='Ej: OK, N/A, Pendiente', max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, db_column='Observaciones', null=True)),
                ('completada', models.BooleanField(db_column='Completada', default=False)),
                ('idordentrabajo', models.ForeignKey(db_column='IDOrdenTrabajo', on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='cmms_api.ordenestrabajo')),
                ('idtareaestandar', models.ForeignKey(db_column='IDTareaEstandar', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.tareasestandar')),
            ],
            options={
                'db_table': 'actividadesordentrabajo',
            },
        ),
        migrations.AddField(
            model_name='planesmantenimiento',
            name='idtipoequipo',
            field=models.ForeignKey(db_column='IDTipoEquipo', on_delete=django.db.models.deletion.CASCADE, to='cmms_api.tiposequipo'),
        ),
        migrations.AddField(
            model_name='tareasestandar',
            name='idtipotarea',
            field=models.ForeignKey(db_column='IDTipoTarea', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.tipostarea'),
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('user', models.OneToOneField(db_column='IDUsuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('cargo', models.CharField(blank=True, db_column='Cargo', max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, db_column='Departamento', max_length=100, null=True)),
                ('idespecialidad', models.ForeignKey(blank=True, db_column='IDEspecialidad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms_api.especialidades')),
                ('idrol', models.ForeignKey(db_column='IDRol', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.roles')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='DetallesPlanMantenimiento',
            fields=[
                ('iddetalleplan', models.AutoField(db_column='IDDetallePlan', primary_key=True, serialize=False)),
                ('intervalohorasoperacion', models.IntegerField(db_column='IntervaloHorasOperacion')),
                ('idplanmantenimiento', models.ForeignKey(db_column='IDPlanMantenimiento', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cmms_api.planesmantenimiento')),
                ('idtareaestandar', models.ForeignKey(db_column='IDTareaEstandar', on_delete=django.db.models.deletion.CASCADE, to='cmms_api.tareasestandar')),
            ],
            options={
                'db_table': 'detallesplanmantenimiento',
                'unique_together': {('idplanmantenimiento', 'idtareaestandar', 'intervalohorasoperacion')},
            },
        ),
    ]
