# Generated by Django 5.2.3 on 2025-06-11 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesPlanMantenimiento',
            fields=[
                ('iddetalleplan', models.AutoField(db_column='IDDetallePlan', primary_key=True, serialize=False)),
                ('puntomantenimiento', models.CharField(blank=True, db_column='PuntoMantenimiento', max_length=20, null=True)),
                ('intervalohorasoperacion', models.IntegerField(blank=True, db_column='IntervaloHorasOperacion', null=True)),
                ('intervalodiascalendario', models.IntegerField(blank=True, db_column='IntervaloDiasCalendario', null=True)),
                ('tipointervalopredominante', models.CharField(blank=True, db_column='TipoIntervaloPredominante', max_length=5, null=True)),
                ('toleranciahoras', models.IntegerField(blank=True, db_column='ToleranciaHoras', null=True)),
                ('toleranciadiana', models.IntegerField(blank=True, db_column='ToleranciaDias', null=True)),
                ('proximoserviciohorometro', models.IntegerField(blank=True, db_column='ProximoServicioHorometro', null=True)),
                ('proximoserviciofecha', models.DateField(blank=True, db_column='ProximoServicioFecha', null=True)),
                ('ultimoserviciohorometro', models.IntegerField(blank=True, db_column='UltimoServicioHorometro', null=True)),
                ('ultimoserviciofecha', models.DateField(blank=True, db_column='UltimoServicioFecha', null=True)),
                ('activoenplan', models.BooleanField(db_column='ActivoEnPlan', default=True)),
            ],
            options={
                'db_table': 'detallesplanmantenimiento',
            },
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('idespecialidad', models.AutoField(db_column='IDEspecialidad', primary_key=True, serialize=False)),
                ('nombreespecialidad', models.CharField(db_column='NombreEspecialidad', max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'especialidades',
            },
        ),
        migrations.CreateModel(
            name='EstadosEquipo',
            fields=[
                ('idestadoequipo', models.AutoField(db_column='IDEstadoEquipo', primary_key=True, serialize=False)),
                ('nombreestado', models.CharField(db_column='NombreEstado', max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
                ('colorindicador', models.CharField(blank=True, db_column='ColorIndicador', max_length=7, null=True)),
            ],
            options={
                'db_table': 'estadosequipo',
            },
        ),
        migrations.CreateModel(
            name='EstadosOrdenTrabajo',
            fields=[
                ('idestadoot', models.AutoField(db_column='IDEstadoOT', primary_key=True, serialize=False)),
                ('nombreestadoot', models.CharField(db_column='NombreEstadoOT', max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'estadosordentrabajo',
            },
        ),
        migrations.CreateModel(
            name='Faenas',
            fields=[
                ('idfaena', models.AutoField(db_column='IDFaena', primary_key=True, serialize=False)),
                ('nombrefaena', models.CharField(db_column='NombreFaena', max_length=100, unique=True)),
                ('ubicacion', models.CharField(blank=True, db_column='Ubicacion', max_length=255, null=True)),
                ('contacto', models.CharField(blank=True, db_column='Contacto', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('activa', models.BooleanField(db_column='Activa', default=True)),
            ],
            options={
                'db_table': 'faenas',
            },
        ),
        migrations.CreateModel(
            name='Repuestos',
            fields=[
                ('idrepuesto', models.AutoField(db_column='IDRepuesto', primary_key=True, serialize=False)),
                ('codigorepuesto', models.CharField(db_column='CodigoRepuesto', max_length=50, unique=True)),
                ('descripcionrepuesto', models.CharField(db_column='DescripcionRepuesto', max_length=255)),
                ('numeropartefabricante', models.CharField(blank=True, db_column='NumeroParteFabricante', max_length=100, null=True)),
                ('idmarcarepuesto', models.IntegerField(blank=True, db_column='IDMarcaRepuesto', null=True)),
                ('idproveedorpreferido', models.IntegerField(blank=True, db_column='IDProveedorPreferido', null=True)),
                ('unidadmedida', models.CharField(db_column='UnidadMedida', max_length=20)),
                ('stockactual', models.DecimalField(db_column='StockActual', decimal_places=2, default=0.0, max_digits=10)),
                ('stockminimo', models.DecimalField(db_column='StockMinimo', decimal_places=2, default=0.0, max_digits=10)),
                ('stockmaximo', models.DecimalField(blank=True, db_column='StockMaximo', decimal_places=2, max_digits=10, null=True)),
                ('ubicacionbodega', models.CharField(blank=True, db_column='UbicacionBodega', max_length=100, null=True)),
                ('costounitariopromedio', models.DecimalField(blank=True, db_column='CostoUnitarioPromedio', decimal_places=2, max_digits=12, null=True)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'db_table': 'repuestos',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('idrol', models.AutoField(db_column='IDRol', primary_key=True, serialize=False)),
                ('nombrerol', models.CharField(db_column='NombreRol', max_length=50, unique=True)),
                ('descripcionrol', models.CharField(blank=True, db_column='DescripcionRol', max_length=255, null=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='TiposEquipo',
            fields=[
                ('idtipoequipo', models.AutoField(db_column='IDTipoEquipo', primary_key=True, serialize=False)),
                ('nombretipo', models.CharField(db_column='NombreTipo', max_length=100, unique=True)),
                ('descripciontipo', models.CharField(blank=True, db_column='DescripcionTipo', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tiposequipo',
            },
        ),
        migrations.CreateModel(
            name='TiposMantenimientoOT',
            fields=[
                ('idtipomantenimientoot', models.AutoField(db_column='IDTipoMantenimientoOT', primary_key=True, serialize=False)),
                ('nombretipomantenimientoot', models.CharField(db_column='NombreTipoMantenimientoOT', max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tiposmantenimientoot',
            },
        ),
        migrations.CreateModel(
            name='TiposTarea',
            fields=[
                ('idtipotarea', models.AutoField(db_column='IDTipoTarea', primary_key=True, serialize=False)),
                ('nombretipotarea', models.CharField(db_column='NombreTipoTarea', max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tipostarea',
            },
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('idequipo', models.AutoField(db_column='IDEquipo', primary_key=True, serialize=False)),
                ('codigointerno', models.CharField(db_column='CodigoInterno', max_length=50, unique=True)),
                ('nombreequipo', models.CharField(db_column='NombreEquipo', max_length=150)),
                ('marca', models.CharField(blank=True, db_column='Marca', max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, db_column='Modelo', max_length=100, null=True)),
                ('aniofabricacion', models.IntegerField(blank=True, db_column='AnioFabricacion', null=True)),
                ('fechaadquisicion', models.DateField(blank=True, db_column='FechaAdquisicion', null=True)),
                ('horometroactual', models.IntegerField(db_column='HorometroActual', default=0)),
                ('fechaultactualizacionhorometro', models.DateTimeField(blank=True, db_column='FechaUltActualizacionHorometro', null=True)),
                ('imagenurl', models.CharField(blank=True, db_column='ImagenURL', max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, db_column='Observaciones', null=True)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
                ('idestadoactual', models.ForeignKey(db_column='IDEstadoActual', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.estadosequipo')),
                ('idfaenaactual', models.ForeignKey(blank=True, db_column='IDFaenaActual', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms_api.faenas')),
                ('idtipoequipo', models.ForeignKey(db_column='IDTipoEquipo', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.tiposequipo')),
            ],
            options={
                'db_table': 'equipos',
            },
        ),
        migrations.CreateModel(
            name='PlanesMantenimiento',
            fields=[
                ('idplanmantenimiento', models.AutoField(db_column='IDPlanMantenimiento', primary_key=True, serialize=False)),
                ('nombreplan', models.CharField(db_column='NombrePlan', max_length=150)),
                ('descripcionplan', models.TextField(blank=True, db_column='DescripcionPlan', null=True)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
                ('version', models.IntegerField(db_column='Version', default=1)),
                ('idequipo', models.ForeignKey(db_column='IDEquipo', on_delete=django.db.models.deletion.CASCADE, to='cmms_api.equipos')),
            ],
            options={
                'db_table': 'planesmantenimiento',
            },
        ),
        migrations.CreateModel(
            name='OrdenesTrabajo',
            fields=[
                ('idordentrabajo', models.AutoField(db_column='IDOrdenTrabajo', primary_key=True, serialize=False)),
                ('numeroot', models.CharField(db_column='NumeroOT', max_length=20, unique=True)),
                ('fechacreacionot', models.DateTimeField(auto_now_add=True, db_column='FechaCreacionOT')),
                ('fechareportefalla', models.DateTimeField(blank=True, db_column='FechaReporteFalla', null=True)),
                ('fechaprogramadainicio', models.DateTimeField(blank=True, db_column='FechaProgramadaInicio', null=True)),
                ('fechaprogramadafin', models.DateTimeField(blank=True, db_column='FechaProgramadaFin', null=True)),
                ('fechaejecucioninicioreal', models.DateTimeField(blank=True, db_column='FechaEjecucionInicioReal', null=True)),
                ('fechaejecucionfinreal', models.DateTimeField(blank=True, db_column='FechaEjecucionFinReal', null=True)),
                ('horometroequipoingreso', models.IntegerField(blank=True, db_column='HorometroEquipoIngreso', null=True)),
                ('horometroequiposalida', models.IntegerField(blank=True, db_column='HorometroEquipoSalida', null=True)),
                ('descripcionproblemareportado', models.TextField(blank=True, db_column='DescripcionProblemaReportado', null=True)),
                ('diagnosticotecnico', models.TextField(blank=True, db_column='DiagnosticoTecnico', null=True)),
                ('causaraizfalla', models.TextField(blank=True, db_column='CausaRaizFalla', null=True)),
                ('solucionaplicada', models.TextField(blank=True, db_column='SolucionAplicada', null=True)),
                ('observacionesot', models.TextField(blank=True, db_column='ObservacionesOT', null=True)),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Urgente', 'Urgente')], db_column='Prioridad', default='Media', max_length=7)),
                ('requieretrasladotaller', models.BooleanField(db_column='RequiereTrasladoTaller', default=False)),
                ('ubicacionrealizacion', models.CharField(blank=True, db_column='UbicacionRealizacion', max_length=100, null=True)),
                ('costoestimadomanoobra', models.DecimalField(blank=True, db_column='CostoEstimadoManoObra', decimal_places=2, max_digits=10, null=True)),
                ('costoestimadorepuestos', models.DecimalField(blank=True, db_column='CostoEstimadoRepuestos', decimal_places=2, max_digits=10, null=True)),
                ('costorealamanoobra', models.DecimalField(blank=True, db_column='CostoRealManoObra', decimal_places=2, max_digits=10, null=True)),
                ('costorealrepuestos', models.DecimalField(blank=True, db_column='CostoRealRepuestos', decimal_places=2, max_digits=10, null=True)),
                ('tiempoinactividadequipohoras', models.DecimalField(blank=True, db_column='TiempoInactividadEquipoHoras', decimal_places=2, max_digits=8, null=True)),
                ('fechacompletada', models.DateTimeField(blank=True, db_column='FechaCompletada', null=True)),
                ('fechaverificada', models.DateTimeField(blank=True, db_column='FechaVerificada', null=True)),
                ('iddetalleplanmantenimientoorigen', models.ForeignKey(blank=True, db_column='IDDetallePlanMantenimientoOrigen', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms_api.detallesplanmantenimiento')),
                ('idequipo', models.ForeignKey(db_column='IDEquipo', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.equipos')),
                ('idestadoot', models.ForeignKey(db_column='IDEstadoOT', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.estadosordentrabajo')),
                ('idplanmantenimientoasociado', models.ForeignKey(blank=True, db_column='IDPlanMantenimientoAsociado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms_api.planesmantenimiento')),
                ('idtipomantenimientoot', models.ForeignKey(db_column='IDTipoMantenimientoOT', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.tiposmantenimientoot')),
            ],
            options={
                'db_table': 'ordenestrabajo',
            },
        ),
        migrations.AddField(
            model_name='detallesplanmantenimiento',
            name='idplanmantenimiento',
            field=models.ForeignKey(db_column='IDPlanMantenimiento', on_delete=django.db.models.deletion.CASCADE, to='cmms_api.planesmantenimiento'),
        ),
        migrations.CreateModel(
            name='TareasEstandar',
            fields=[
                ('idtareaestandar', models.AutoField(db_column='IDTareaEstandar', primary_key=True, serialize=False)),
                ('codigotarea', models.CharField(db_column='CodigoTarea', max_length=20, unique=True)),
                ('descripciontarea', models.TextField(db_column='DescripcionTarea')),
                ('duracionestimadaminutos', models.IntegerField(blank=True, db_column='DuracionEstimadaMinutos', null=True)),
                ('instruccionesdetalladas', models.TextField(blank=True, db_column='InstruccionesDetalladas', null=True)),
                ('materialessugeridos', models.TextField(blank=True, db_column='MaterialesSugeridos', null=True)),
                ('requiereparadaequipo', models.BooleanField(db_column='RequiereParadaEquipo', default=True)),
                ('activa', models.BooleanField(db_column='Activa', default=True)),
                ('idespecialidadrequerida', models.ForeignKey(blank=True, db_column='IDEspecialidadRequerida', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms_api.especialidades')),
                ('idtipotarea', models.ForeignKey(db_column='IDTipoTarea', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.tipostarea')),
            ],
            options={
                'db_table': 'tareasestandar',
            },
        ),
        migrations.AddField(
            model_name='detallesplanmantenimiento',
            name='idtareaestandar',
            field=models.ForeignKey(db_column='IDTareaEstandar', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.tareasestandar'),
        ),
        migrations.CreateModel(
            name='ActividadesOrdenTrabajo',
            fields=[
                ('idactividadot', models.AutoField(db_column='IDActividadOT', primary_key=True, serialize=False)),
                ('secuencia', models.IntegerField(blank=True, db_column='Secuencia', null=True)),
                ('descripcionactividad', models.TextField(db_column='DescripcionActividad')),
                ('fechainicioactividad', models.DateTimeField(blank=True, db_column='FechaInicioActividad', null=True)),
                ('fechafinactividad', models.DateTimeField(blank=True, db_column='FechaFinActividad', null=True)),
                ('tiempoestimadominutos', models.IntegerField(blank=True, db_column='TiempoEstimadoMinutos', null=True)),
                ('tiemporealminutos', models.IntegerField(blank=True, db_column='TiempoRealMinutos', null=True)),
                ('observacionesactividad', models.TextField(blank=True, db_column='ObservacionesActividad', null=True)),
                ('completada', models.BooleanField(db_column='Completada', default=False)),
                ('resultadoinspeccion', models.CharField(blank=True, db_column='ResultadoInspeccion', max_length=50, null=True)),
                ('medicionvalor', models.DecimalField(blank=True, db_column='MedicionValor', decimal_places=2, max_digits=10, null=True)),
                ('unidadmedicion', models.CharField(blank=True, db_column='UnidadMedicion', max_length=20, null=True)),
                ('idordentrabajo', models.ForeignKey(db_column='IDOrdenTrabajo', on_delete=django.db.models.deletion.CASCADE, to='cmms_api.ordenestrabajo')),
                ('idtareaestandar', models.ForeignKey(blank=True, db_column='IDTareaEstandar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms_api.tareasestandar')),
            ],
            options={
                'db_table': 'actividadesordentrabajo',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('user', models.OneToOneField(db_column='IDUsuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('fechaultactualizacion', models.DateTimeField(auto_now=True, db_column='FechaUltActualizacion')),
                ('ultimoacceso', models.DateTimeField(blank=True, db_column='UltimoAcceso', null=True)),
                ('idespecialidad', models.ForeignKey(blank=True, db_column='IDEspecialidad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms_api.especialidades')),
                ('idrol', models.ForeignKey(db_column='IDRol', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.roles')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='UsoRepuestosActividadOT',
            fields=[
                ('idusorepuesto', models.AutoField(db_column='IDUsoRepuesto', primary_key=True, serialize=False)),
                ('cantidadusada', models.DecimalField(db_column='CantidadUsada', decimal_places=2, max_digits=10)),
                ('fechauso', models.DateTimeField(auto_now_add=True, db_column='FechaUso')),
                ('costoalmomentodeuso', models.DecimalField(blank=True, db_column='CostoAlMomentoDeUso', decimal_places=2, max_digits=12, null=True)),
                ('idactividadot', models.ForeignKey(db_column='IDActividadOT', on_delete=django.db.models.deletion.CASCADE, to='cmms_api.actividadesordentrabajo')),
                ('idrepuesto', models.ForeignKey(db_column='IDRepuesto', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.repuestos')),
                ('idusuarioregistra', models.ForeignKey(blank=True, db_column='IDUsuarioRegistra', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms_api.usuarios')),
            ],
            options={
                'db_table': 'usorepuestosactividadot',
            },
        ),
        migrations.AddField(
            model_name='planesmantenimiento',
            name='idusuariocreador',
            field=models.ForeignKey(blank=True, db_column='IDUsuarioCreador', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms_api.usuarios'),
        ),
        migrations.AddField(
            model_name='ordenestrabajo',
            name='completadapor',
            field=models.ForeignKey(blank=True, db_column='CompletadaPor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_completadas', to='cmms_api.usuarios'),
        ),
        migrations.AddField(
            model_name='ordenestrabajo',
            name='idreportadopor',
            field=models.ForeignKey(blank=True, db_column='IDReportadoPor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_reportadas', to='cmms_api.usuarios'),
        ),
        migrations.AddField(
            model_name='ordenestrabajo',
            name='idsolicitante',
            field=models.ForeignKey(db_column='IDSolicitante', on_delete=django.db.models.deletion.PROTECT, related_name='ots_solicitadas', to='cmms_api.usuarios'),
        ),
        migrations.AddField(
            model_name='ordenestrabajo',
            name='idtecnicoasignadoprincipal',
            field=models.ForeignKey(blank=True, db_column='IDTecnicoAsignadoPrincipal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_asignadas', to='cmms_api.usuarios'),
        ),
        migrations.AddField(
            model_name='ordenestrabajo',
            name='verificadapor',
            field=models.ForeignKey(blank=True, db_column='VerificadaPor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_verificadas', to='cmms_api.usuarios'),
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('idnotificacion', models.AutoField(db_column='IDNotificacion', primary_key=True, serialize=False)),
                ('mensaje', models.TextField(db_column='Mensaje')),
                ('tiponotificacion', models.CharField(blank=True, db_column='TipoNotificacion', max_length=50, null=True)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('fechalectura', models.DateTimeField(blank=True, db_column='FechaLectura', null=True)),
                ('leida', models.BooleanField(db_column='Leida', default=False)),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], db_column='Prioridad', default='Media', max_length=5)),
                ('urlrelacionada', models.CharField(blank=True, db_column='URLRelacionada', max_length=255, null=True)),
                ('identidadrelacionada', models.IntegerField(blank=True, db_column='IDEntidadRelacionada', null=True)),
                ('tipoentidadrelacionada', models.CharField(blank=True, db_column='TipoEntidadRelacionada', max_length=50, null=True)),
                ('idusuariodestino', models.ForeignKey(db_column='IDUsuarioDestino', on_delete=django.db.models.deletion.CASCADE, to='cmms_api.usuarios')),
            ],
            options={
                'db_table': 'notificaciones',
            },
        ),
        migrations.CreateModel(
            name='HistorialHorometros',
            fields=[
                ('idhistorialhorometro', models.AutoField(db_column='IDHistorialHorometro', primary_key=True, serialize=False)),
                ('fechalectura', models.DateTimeField(auto_now_add=True, db_column='FechaLectura')),
                ('valorhorometro', models.IntegerField(db_column='ValorHorometro')),
                ('fuentelectura', models.CharField(blank=True, db_column='FuenteLectura', max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, db_column='Observaciones', null=True)),
                ('idequipo', models.ForeignKey(db_column='IDEquipo', on_delete=django.db.models.deletion.CASCADE, to='cmms_api.equipos')),
                ('idordentrabajoasociada', models.ForeignKey(blank=True, db_column='IDOrdenTrabajoAsociada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms_api.ordenestrabajo')),
                ('idusuarioregistra', models.ForeignKey(blank=True, db_column='IDUsuarioRegistra', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms_api.usuarios')),
            ],
            options={
                'db_table': 'historialhorometros',
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadosEquipo',
            fields=[
                ('idhistorialestado', models.AutoField(db_column='IDHistorialEstado', primary_key=True, serialize=False)),
                ('fechacambioestado', models.DateTimeField(auto_now_add=True, db_column='FechaCambioEstado')),
                ('motivocambio', models.CharField(blank=True, db_column='MotivoCambio', max_length=255, null=True)),
                ('idequipo', models.ForeignKey(db_column='IDEquipo', on_delete=django.db.models.deletion.CASCADE, to='cmms_api.equipos')),
                ('idestadoequipoanterior', models.ForeignKey(blank=True, db_column='IDEstadoEquipoAnterior', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_como_anterior', to='cmms_api.estadosequipo')),
                ('idestadoequiponuevo', models.ForeignKey(db_column='IDEstadoEquipoNuevo', on_delete=django.db.models.deletion.PROTECT, related_name='historiales_como_nuevo', to='cmms_api.estadosequipo')),
                ('idordentrabajorelacionada', models.ForeignKey(blank=True, db_column='IDOrdenTrabajoRelacionada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms_api.ordenestrabajo')),
                ('idusuarioresponsable', models.ForeignKey(blank=True, db_column='IDUsuarioResponsable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms_api.usuarios')),
            ],
            options={
                'db_table': 'historialestadosequipo',
            },
        ),
        migrations.AddField(
            model_name='equipos',
            name='idoperarioasignadopredeterminado',
            field=models.ForeignKey(blank=True, db_column='IDOperarioAsignadoPredeterminado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms_api.usuarios'),
        ),
        migrations.CreateModel(
            name='DocumentosAdjuntos',
            fields=[
                ('iddocumento', models.AutoField(db_column='IDDocumento', primary_key=True, serialize=False)),
                ('nombrearchivooriginal', models.CharField(db_column='NombreArchivoOriginal', max_length=255)),
                ('patharchivoservidor', models.CharField(db_column='PathArchivoServidor', max_length=500)),
                ('tipomime', models.CharField(blank=True, db_column='TipoMIME', max_length=100, null=True)),
                ('tamanobytes', models.BigIntegerField(blank=True, db_column='TamanoBytes', null=True)),
                ('descripcionadjunto', models.CharField(blank=True, db_column='DescripcionAdjunto', max_length=255, null=True)),
                ('fechasubida', models.DateTimeField(auto_now_add=True, db_column='FechaSubida')),
                ('entidadasociada', models.CharField(db_column='EntidadAsociada', max_length=50)),
                ('identidadasociada', models.IntegerField(db_column='IDEntidadAsociada')),
                ('idusuariosube', models.ForeignKey(blank=True, db_column='IDUsuarioSube', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms_api.usuarios')),
            ],
            options={
                'db_table': 'documentosadjuntos',
            },
        ),
        migrations.CreateModel(
            name='Agendas',
            fields=[
                ('idagenda', models.AutoField(db_column='IDAgenda', primary_key=True, serialize=False)),
                ('tituloevento', models.CharField(db_column='TituloEvento', max_length=255)),
                ('fechahorainicio', models.DateTimeField(db_column='FechaHoraInicio')),
                ('fechahorafin', models.DateTimeField(db_column='FechaHoraFin')),
                ('descripcionevento', models.TextField(blank=True, db_column='DescripcionEvento', null=True)),
                ('tipoevento', models.CharField(blank=True, db_column='TipoEvento', max_length=50, null=True)),
                ('colorevento', models.CharField(blank=True, db_column='ColorEvento', max_length=7, null=True)),
                ('esdiacompleto', models.BooleanField(db_column='EsDiaCompleto', default=False)),
                ('recursivo', models.BooleanField(db_column='Recursivo', default=False)),
                ('reglarecursividad', models.CharField(blank=True, db_column='ReglaRecursividad', max_length=255, null=True)),
                ('fechacreacionevento', models.DateTimeField(auto_now_add=True, db_column='FechaCreacionEvento')),
                ('idequipo', models.ForeignKey(blank=True, db_column='IDEquipo', null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms_api.equipos')),
                ('idordentrabajo', models.ForeignKey(blank=True, db_column='IDOrdenTrabajo', null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms_api.ordenestrabajo')),
                ('idplanmantenimiento', models.ForeignKey(blank=True, db_column='IDPlanMantenimiento', null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms_api.planesmantenimiento')),
                ('idusuarioasignado', models.ForeignKey(blank=True, db_column='IDUsuarioAsignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_asignados', to='cmms_api.usuarios')),
                ('idusuariocreador', models.ForeignKey(blank=True, db_column='IDUsuarioCreador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_creados', to='cmms_api.usuarios')),
            ],
            options={
                'db_table': 'agendas',
            },
        ),
        migrations.AddField(
            model_name='actividadesordentrabajo',
            name='idtecnicoejecutor',
            field=models.ForeignKey(blank=True, db_column='IDTecnicoEjecutor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms_api.usuarios'),
        ),
        migrations.AlterUniqueTogether(
            name='detallesplanmantenimiento',
            unique_together={('idplanmantenimiento', 'idtareaestandar', 'intervalohorasoperacion', 'intervalodiascalendario')},
        ),
        migrations.AlterUniqueTogether(
            name='planesmantenimiento',
            unique_together={('idequipo', 'nombreplan')},
        ),
    ]
