# Generated by Django 5.2.3 on 2025-06-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenestrabajo',
            name='numeroot',
            field=models.CharField(db_column='NumeroOT', max_length=50, unique=True),
        ),
    ]
