# Generated by Django 4.2.23 on 2025-06-23 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmms_api', '0002_alter_ordenestrabajo_numeroot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistAnswer',
            fields=[
                ('id_answer', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('bueno', 'Bueno'), ('malo', 'Malo'), ('na', 'No Aplica')], max_length=10)),
                ('observacion_item', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistCategory',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistInstance',
            fields=[
                ('id_instance', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inspeccion', models.DateField()),
                ('horometro_inspeccion', models.IntegerField()),
                ('lugar_inspeccion', models.CharField(blank=True, max_length=200, null=True)),
                ('observaciones_generales', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=255)),
                ('es_critico', models.BooleanField(default=False, help_text='Marcar si una falla en este ítem impide la operación del equipo.')),
                ('orden', models.IntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cmms_api.checklistcategory')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id_template', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='detallesplanmantenimiento',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='actividadesordentrabajo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='actividadesordentrabajo',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='estadosequipo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='faenas',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='faenas',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='ordenestrabajo',
            name='fechaautorizacion',
        ),
        migrations.RemoveField(
            model_name='ordenestrabajo',
            name='firma_solicitante',
        ),
        migrations.RemoveField(
            model_name='ordenestrabajo',
            name='firma_tecnico',
        ),
        migrations.RemoveField(
            model_name='ordenestrabajo',
            name='idautorizadopor',
        ),
        migrations.RemoveField(
            model_name='ordenestrabajo',
            name='observacionesgenerales',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='descripcionrol',
        ),
        migrations.RemoveField(
            model_name='tareasestandar',
            name='procedimiento',
        ),
        migrations.RemoveField(
            model_name='tiposequipo',
            name='descripciontipo',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='idespecialidad',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='telefono',
        ),
        migrations.AddField(
            model_name='actividadesordentrabajo',
            name='descripcionactividad',
            field=models.TextField(db_column='DescripcionActividad', default='Actividad de mantenimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividadesordentrabajo',
            name='fechafinactividad',
            field=models.DateTimeField(blank=True, db_column='FechaFinActividad', null=True),
        ),
        migrations.AddField(
            model_name='actividadesordentrabajo',
            name='fechainicioactividad',
            field=models.DateTimeField(blank=True, db_column='FechaInicioActividad', null=True),
        ),
        migrations.AddField(
            model_name='actividadesordentrabajo',
            name='idtecnicoejecutor',
            field=models.ForeignKey(blank=True, db_column='IDTecnicoEjecutor', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actividadesordentrabajo',
            name='medicionvalor',
            field=models.DecimalField(blank=True, db_column='MedicionValor', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='actividadesordentrabajo',
            name='observacionesactividad',
            field=models.TextField(blank=True, db_column='ObservacionesActividad', null=True),
        ),
        migrations.AddField(
            model_name='actividadesordentrabajo',
            name='resultadoinspeccion',
            field=models.CharField(blank=True, db_column='ResultadoInspeccion', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='actividadesordentrabajo',
            name='secuencia',
            field=models.IntegerField(blank=True, db_column='Secuencia', null=True),
        ),
        migrations.AddField(
            model_name='actividadesordentrabajo',
            name='tiempoestimadominutos',
            field=models.IntegerField(blank=True, db_column='TiempoEstimadoMinutos', null=True),
        ),
        migrations.AddField(
            model_name='actividadesordentrabajo',
            name='tiemporealminutos',
            field=models.IntegerField(blank=True, db_column='TiempoRealMinutos', null=True),
        ),
        migrations.AddField(
            model_name='actividadesordentrabajo',
            name='unidadmedicion',
            field=models.CharField(blank=True, db_column='UnidadMedicion', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agendas',
            name='colorevento',
            field=models.CharField(blank=True, db_column='ColorEvento', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='agendas',
            name='esdiacompleto',
            field=models.BooleanField(db_column='EsDiaCompleto', default=False),
        ),
        migrations.AddField(
            model_name='agendas',
            name='fechacreacionevento',
            field=models.DateTimeField(auto_now_add=True, db_column='FechaCreacionEvento', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendas',
            name='idequipo',
            field=models.ForeignKey(blank=True, db_column='IDEquipo', null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms_api.equipos'),
        ),
        migrations.AddField(
            model_name='agendas',
            name='idplanmantenimiento',
            field=models.ForeignKey(blank=True, db_column='IDPlanMantenimiento', null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms_api.planesmantenimiento'),
        ),
        migrations.AddField(
            model_name='agendas',
            name='idusuarioasignado',
            field=models.ForeignKey(blank=True, db_column='IDUsuarioAsignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendas',
            name='idusuariocreador',
            field=models.ForeignKey(db_column='IDUsuarioCreador', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_creados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendas',
            name='recursivo',
            field=models.BooleanField(db_column='Recursivo', default=False),
        ),
        migrations.AddField(
            model_name='agendas',
            name='reglarecursividad',
            field=models.CharField(blank=True, db_column='ReglaRecursividad', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detallesplanmantenimiento',
            name='activo',
            field=models.BooleanField(db_column='Activo', default=True),
        ),
        migrations.AddField(
            model_name='detallesplanmantenimiento',
            name='escritic',
            field=models.BooleanField(db_column='EsCritica', default=False),
        ),
        migrations.AddField(
            model_name='equipos',
            name='anio',
            field=models.IntegerField(blank=True, db_column='Anio', null=True),
        ),
        migrations.AddField(
            model_name='equipos',
            name='patente',
            field=models.CharField(blank=True, db_column='Patente', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ordenestrabajo',
            name='descripcionproblemareportado',
            field=models.TextField(blank=True, db_column='DescripcionProblemaReportado', null=True),
        ),
        migrations.AddField(
            model_name='ordenestrabajo',
            name='fechacompletado',
            field=models.DateTimeField(blank=True, db_column='FechaCompletado', null=True),
        ),
        migrations.AddField(
            model_name='ordenestrabajo',
            name='fechareportefalla',
            field=models.DateTimeField(blank=True, db_column='FechaReporteFalla', null=True),
        ),
        migrations.AddField(
            model_name='ordenestrabajo',
            name='observacionesfinales',
            field=models.TextField(blank=True, db_column='ObservacionesFinales', null=True),
        ),
        migrations.AddField(
            model_name='ordenestrabajo',
            name='prioridad',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Crítica', 'Crítica')], db_column='Prioridad', default='Media', max_length=20),
        ),
        migrations.AddField(
            model_name='ordenestrabajo',
            name='tiempototalminutos',
            field=models.IntegerField(blank=True, db_column='TiempoTotalMinutos', null=True),
        ),
        migrations.AddField(
            model_name='planesmantenimiento',
            name='descripcionplan',
            field=models.TextField(blank=True, db_column='DescripcionPlan', null=True),
        ),
        migrations.AddField(
            model_name='planesmantenimiento',
            name='fechacreacion',
            field=models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tareasestandar',
            name='nombretarea',
            field=models.CharField(db_column='NombreTarea', default='Tarea estándar', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tareasestandar',
            name='tiempoestimadominutos',
            field=models.IntegerField(db_column='TiempoEstimadoMinutos', default=0),
        ),
        migrations.AlterField(
            model_name='actividadesordentrabajo',
            name='idordentrabajo',
            field=models.ForeignKey(db_column='IDOrdenTrabajo', on_delete=django.db.models.deletion.CASCADE, to='cmms_api.ordenestrabajo'),
        ),
        migrations.AlterField(
            model_name='actividadesordentrabajo',
            name='idtareaestandar',
            field=models.ForeignKey(blank=True, db_column='IDTareaEstandar', null=True, on_delete=django.db.models.deletion.PROTECT, to='cmms_api.tareasestandar'),
        ),
        migrations.AlterField(
            model_name='detallesplanmantenimiento',
            name='idplanmantenimiento',
            field=models.ForeignKey(db_column='IDPlanMantenimiento', on_delete=django.db.models.deletion.CASCADE, to='cmms_api.planesmantenimiento'),
        ),
        migrations.AlterField(
            model_name='detallesplanmantenimiento',
            name='idtareaestandar',
            field=models.ForeignKey(db_column='IDTareaEstandar', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.tareasestandar'),
        ),
        migrations.AlterField(
            model_name='detallesplanmantenimiento',
            name='intervalohorasoperacion',
            field=models.IntegerField(db_column='IntervaloHorasOperacion', help_text='Cada cuántas horas se debe realizar esta tarea'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='codigointerno',
            field=models.CharField(blank=True, db_column='CodigoInterno', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='estadosordentrabajo',
            name='descripcion',
            field=models.TextField(blank=True, db_column='Descripcion', null=True),
        ),
        migrations.AlterField(
            model_name='ordenestrabajo',
            name='idtecnicoasignado',
            field=models.ForeignKey(blank=True, db_column='IDTecnicoAsignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planesmantenimiento',
            name='idtipoequipo',
            field=models.ForeignKey(db_column='IDTipoEquipo', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.tiposequipo'),
        ),
        migrations.AlterField(
            model_name='planesmantenimiento',
            name='nombreplan',
            field=models.CharField(db_column='NombrePlan', max_length=255),
        ),
        migrations.AlterField(
            model_name='tareasestandar',
            name='descripciontarea',
            field=models.TextField(blank=True, db_column='DescripcionTarea', null=True),
        ),
        migrations.AlterField(
            model_name='tiposmantenimientoot',
            name='descripcion',
            field=models.TextField(blank=True, db_column='Descripcion', null=True),
        ),
        migrations.AlterField(
            model_name='tiposmantenimientoot',
            name='nombretipomantenimientoot',
            field=models.CharField(db_column='NombreTipoMantenimientoOT', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tipostarea',
            name='descripcion',
            field=models.TextField(blank=True, db_column='Descripcion', null=True),
        ),
        migrations.DeleteModel(
            name='Especialidades',
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='tipo_equipo',
            field=models.ForeignKey(help_text='Tipo de equipo al que aplica este checklist.', on_delete=django.db.models.deletion.CASCADE, to='cmms_api.tiposequipo'),
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmms_api.equipos'),
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmms_api.checklisttemplate'),
        ),
        migrations.AddField(
            model_name='checklistcategory',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='cmms_api.checklisttemplate'),
        ),
        migrations.AddField(
            model_name='checklistanswer',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='cmms_api.checklistinstance'),
        ),
        migrations.AddField(
            model_name='checklistanswer',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmms_api.checklistitem'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistanswer',
            unique_together={('instance', 'item')},
        ),
    ]
