# Generated by Django 4.2.23 on 2025-06-23 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms_api', '0003_checklistanswer_checklistcategory_checklistinstance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividadesordentrabajo',
            options={'ordering': ['secuencia']},
        ),
        migrations.AlterModelOptions(
            name='agendas',
            options={'ordering': ['fechahorainicio']},
        ),
        migrations.AlterModelOptions(
            name='checklistanswer',
            options={'ordering': ['item__orden']},
        ),
        migrations.AlterModelOptions(
            name='checklistinstance',
            options={'ordering': ['-fecha_inspeccion']},
        ),
        migrations.AlterModelOptions(
            name='checklisttemplate',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='detallesplanmantenimiento',
            options={'ordering': ['intervalohorasoperacion']},
        ),
        migrations.AlterModelOptions(
            name='equipos',
            options={'ordering': ['nombreequipo']},
        ),
        migrations.AlterModelOptions(
            name='estadosequipo',
            options={'ordering': ['nombreestado']},
        ),
        migrations.AlterModelOptions(
            name='estadosordentrabajo',
            options={'ordering': ['nombreestadoot']},
        ),
        migrations.AlterModelOptions(
            name='faenas',
            options={'ordering': ['nombrefaena']},
        ),
        migrations.AlterModelOptions(
            name='ordenestrabajo',
            options={'ordering': ['-fechacreacionot']},
        ),
        migrations.AlterModelOptions(
            name='planesmantenimiento',
            options={'ordering': ['nombreplan']},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'ordering': ['nombrerol']},
        ),
        migrations.AlterModelOptions(
            name='tareasestandar',
            options={'ordering': ['nombretarea']},
        ),
        migrations.AlterModelOptions(
            name='tiposequipo',
            options={'ordering': ['nombretipo']},
        ),
        migrations.AlterModelOptions(
            name='tiposmantenimientoot',
            options={'ordering': ['nombretipomantenimientoot']},
        ),
        migrations.AlterModelOptions(
            name='tipostarea',
            options={'ordering': ['nombretipotarea']},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'ordering': ['user__username']},
        ),
        migrations.RemoveField(
            model_name='equipos',
            name='horometroactual',
        ),
    ]
