# Generated by Django 5.2.3 on 2025-06-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms_api', '0004_alter_actividadesordentrabajo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistinstance',
            name='imagen_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencias/'),
        ),
    ]
