# Generated by Django 4.2.23 on 2025-06-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms_api', '0005_checklistinstance_imagen_evidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistinstance',
            name='imagen_evidencia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
