# Generated by Django 4.2.23 on 2025-06-30 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmms_api', '0006_alter_checklistinstance_imagen_evidencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaOT',
            fields=[
                ('idevidencia', models.AutoField(db_column='IDEvidencia', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
                ('imagen_base64', models.TextField(db_column='ImagenBase64', help_text='Imagen almacenada en formato Base64')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, db_column='FechaSubida')),
                ('idordentrabajo', models.ForeignKey(db_column='IDOrdenTrabajo', on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='cmms_api.ordenestrabajo')),
                ('usuario_subida', models.ForeignKey(db_column='UsuarioSubida', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evidenciaot',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
