# Generated by Django 4.2.23 on 2025-07-09 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmms_api', '0007_evidenciaot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciaot',
            name='usuario_subida',
            field=models.ForeignKey(blank=True, db_column='UsuarioSubida', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChecklistImage',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción opcional de la imagen', max_length=255, null=True)),
                ('imagen_base64', models.TextField(help_text='Imagen almacenada en formato Base64')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='cmms_api.checklistinstance')),
                ('usuario_subida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'checklistimage',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
